version: '2.1'
 
services:
  users-db:
    container_name: users-db
    build: ./users-api/db
    ports:
       - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0
  images-db:
    container_name: images-db
    build: ./images-api/db
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0